# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_comment_food'),
        ('userauth', '0002_auto_20181114_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hate_foods',
            field=models.ManyToManyField(blank=True, related_name='hate_foods', to='post.Food'),
        ),
    ]
