# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_comment_food'),
        ('userauth', '0004_user_like_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='siruh_foods',
            field=models.ManyToManyField(blank=True, related_name='siruh_foods', to='post.Food'),
        ),
        migrations.AddField(
            model_name='user',
            name='sunho_foods',
            field=models.ManyToManyField(blank=True, related_name='sunho_foods', to='post.Food'),
        ),
    ]
