# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_auto_20181123_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='siruh_foods',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sunho_foods',
        ),
    ]
