# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20181120_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='provider',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, related_name='foodprovider', to='post.Provider'),
            preserve_default=False,
        ),
    ]
