# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_food_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='provider',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, related_name='foodprovider', to='post.Provider'),
        ),
    ]
