# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20181120_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='food',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, related_name='comment_food', to='post.Food'),
            preserve_default=False,
        ),
    ]
