# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_comment_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='food',
        ),
    ]
