# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20181123_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='food',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments_food', to='post.Food'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='post.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='provider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments_provider', to='post.Provider'),
        ),
    ]
