# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20181123_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='food',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='provider',
        ),
    ]
